apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tb-http-loadbalancer-external
  namespace: thingsboard
spec:
  tls:
    - secretName: ssl-cert-secret
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080